import { minify } from "html-minifier";
import fs from "fs";

const options = {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: true,
  minifyCSS: true,
  minifyJS: true,
  minifyURLs: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
};

const path = { src: "./src/index.html", dest: "./dist/index.html" };

fs.readFile(path.src, "utf8", (err, html) => {
  if (err) {
    console.error("Error reading file:", err);
    return;
  }

  const htmlMinified = minify(html, options);

  fs.writeFile(path.dest, htmlMinified, (err) => {
    if (err) {
      console.error(err);
    } else {
      // file written successfully
    }
  });
});
